name: Renew PAT Token

on:
  schedule:
    - cron: '0 0 1 */1 *'  # Runs on the first day of every month

jobs:
  renew-pat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.PIPELINE_RENEWAL_GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Generate new PAT
        id: generate_pat
        run: |
          NEW_PAT=$(gh auth refresh -h github.com -s "repo,workflow,admin:org" -d "Automated Token Renewal for SSL" -t)
          echo "NEW_PAT=$NEW_PAT" >> $GITHUB_ENV

      - name: Update GitHub Secret
        run: |
          echo "${{ env.NEW_PAT }}" | gh secret set PIPELINE_RENEWAL_GITHUB_TOKEN --body -
