name: Renew PAT Token

on:
  schedule:
    - cron: '0 0 1 */1 *'

jobs:
  renew-pat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate new PAT
        id: generate_pat
        run: |          
          NEW_PAT=$(curl -X POST -H "Authorization: token ${{ secrets.PIPELINE_RENEWAL_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/user/tokens \
            -d '{"scopes":["repo"],"note":"Renewed PAT"}' | jq -r '.token')
          echo "NEW_PAT=$NEW_PAT" >> $GITHUB_ENV

      - name: Update GitHub Secret
        run: |
          curl -X PUT -H "Authorization: token ${{ secrets.PIPELINE_RENEWAL_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/mari-code-sudo/bedrock/actions/secrets/PIPELINE_RENEWAL_GITHUB_TOKEN \
            -d '{"encrypted_value":"'"$(echo -n $NEW_PAT | openssl enc -aes-256-cbc -a -salt -pass pass:${{ secrets.PIPELINE_RENEWAL_GITHUB_TOKEN }})"'"}'
