name: Renew PAT Token

on:
  schedule:
    - cron: '0 0 1 */1 *'  # Runs on the first day of every month
  workflow_dispatch:  # Allows manual triggering

jobs:
  renew-pat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Authenticate with GitHub App
        id: auth
        run: |
          APP_ID=1189838
          INSTALLATION_ID=Iv23lifodvXbyMlxqQyD
          PRIVATE_KEY=$(echo "${{ secrets.PAT_APP_PRIVATE_KEY }}" | base64 -d)
          echo =$PRIVATE_KEY

          JWT=$(ruby -r openssl -r base64 -r json -e 'payload = { iat: Time.now.to_i, exp: Time.now.to_i + 600, iss: ENV["APP_ID"] }; key = OpenSSL::PKey::RSA.new(ENV["PRIVATE_KEY"]); token = JWT.encode(payload, key, "RS256"); puts token')
          ACCESS_TOKEN=$(curl -s -X POST -H "Authorization: Bearer $JWT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/app/installations/$INSTALLATION_ID/access_tokens | jq -r .token)

          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Generate new PAT
        id: generate_pat
        run: |
          NEW_PAT=$(curl -s -X POST -H "Authorization: token $ACCESS_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/user/tokens -d '{"scopes":["repo","workflow","admin:org"],"note":"Automated Token Renewal for SSL"}' | jq -r '.token')
          echo "NEW_PAT=$NEW_PAT" >> $GITHUB_ENV

      - name: Update GitHub Secret
        run: |
          echo "${{ env.NEW_PAT }}" | gh secret set PIPELINE_RENEWAL_GITHUB_TOKEN --body -
