name: RenewPATToken

on:
  schedule:
    - cron: '0 0 1 */1 *'  # Runs on the first day of every month
  workflow_dispatch:  # Allows manual triggering

jobs:
  renew-pat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          # Download the latest GitHub CLI release
          curl -LO https://github.com/cli/cli/releases/latest/download/gh_2.0.0_linux_amd64.tar.gz

          # Extract the tarball
          tar -xzf gh_2.0.0_linux_amd64.tar.gz

          # Move the binary to a directory in your PATH
          sudo mv gh_2.0.0_linux_amd64/bin/gh /usr/local/bin/

          # Verify the installation
          gh --version

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.PIPELINE_RENEWAL_GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Generate new PAT
        id: generate_pat
        run: |
          NEW_PAT=$(gh auth refresh -h github.com -s "repo,workflow,admin:org" -d "Automated Token Renewal for SSL" -t)
          echo "NEW_PAT=$NEW_PAT" >> $GITHUB_ENV

      - name: Update GitHub Secret
        run: |
          echo "${{ env.NEW_PAT }}" | gh secret set PIPELINE_RENEWAL_GITHUB_TOKEN --body -
